rl-90/liveness Liveness:
regulaforensics/FaceRecognition-web-openapi pull request #8
Opened 2020-09-30 23:21 UTC by alshund

- add liveness endpoints open api definition without components descriptions

2020-10-01 08:53 UTC, hleb-albau requested changes
fill all desc and summaries

2020-10-01 08:53 UTC, hleb-albau commented on index.yml
> +  /liveness:
other liveness paths ?

2020-10-01 08:53 UTC, hleb-albau commented on liveness.yml
> +/liveness/depth:
forgot space?

2020-10-01 08:53 UTC, hleb-albau commented on liveness.yml
> +      summary: ""
empty summary

2020-10-01 08:53 UTC, hleb-albau commented on liveness.yml
> +          description: ""
empty desc

2020-10-05 10:37 UTC, alshund commented
@dimkasss можешь посмотреть descriptions? Мб ты можешь что-то более точнее описать?

2020-10-05 14:05 UTC, ikliashchou commented on liveness.yml
> +        code:
should be enum for this code value

2020-10-05 14:19 UTC, ikliashchou commented
There is an enum for error codes from core lib. We need to add it to API desc as FaceRErrorCodes

enum eFaceRProcessorErrorCodes
{
   FACER_OK = 0,
   FACER_NO_LICENSE = 200,
   FACER_IS_NOT_INITIALIZED = 201,
   FACER_COMMAND_IS_NOT_SUPPORTED = 202,
   FACER_COMMAND_PARAMS_READ_ERROR = 203,
   FACER_SEARCHER_INDEX_FILE_NOT_EXIST = 204,
   FACER_SEARCHER_INDEX_FILE_READ_ERROR = 205,
   FACER_SEARCHER_INDEX_FILE_DECRYPTION_ERROR = 206,
   FACER_SEARCHER_INDEX_LOAD_ERROR = 207,
   FACER_SEARCHER_WRONG_DESCRIPTOR_VERSION = 208,
   FACER_SEARCHER_INDEX_FILE_ENCRYPTION_ERROR = 209,
   FACER_SEARCHER_INDEX_FILE_SAVE_ERROR = 210,
   FACER_SEARCHER_IMAGE_DECODE_ERROR = 211,
   FACER_SEARCHER_ID_EXISTS_IN_INDEX = 212,
   FACER_SEARCHER_ID_NOT_IN_INDEX = 213,
   FACER_SEARCHER_NO_FACES = 214,
   FACER_SEARCHER_DESCRIPTOR_EXTRACTOR_ERROR = 215,
   FACER_SEARCHER_METADATA_READ_ERROR = 216,
   FACER_SEARCHER_NO_SEARCH_LICENSE = 217,
   FACER_SEARCHER_DESCRIPTOR_DECODE_ERROR = 218,
   FACER_SEARCHER_DESCRIPTOR_WRONG_SIZE = 219,
   FACER_SEARCHER_ZIP_IMAGE_READ_ERROR = 220,
   FACER_SEARCHER_ZIP_META_READ_ERROR = 221,
   FACER_SEARCHER_SIMILAR_PHOTOS_EXIST = 222,
   FACER_SEARCHER_PERSON_ZIP_READ_ERROR = 223,
   FACER_LESS_THAN_TWO_IMAGES_IN_REQUEST = 224,
   FACER_SEARCHER_WRONG_ID = 225,
   FACER_SEARCHER_ID_EXISTS_IN_DELETED = 226,
   FACER_VIDEO_DECODE_ERROR = 227,
   FACER_NOT_ENOUGH_FRAMES = 228,
   FACER_OUTPUT_IS_NOT_DEFINED = 229
};

2020-10-07 13:24 UTC, ikliashchou approved these changes

2020-10-07 13:27 UTC, merged